#Comparision(Relational) Operators(Binary)
print(10==10)
print("hi"=="hi")
print("hi"=="Hi")
print(10!=5)
print(10>4)
print("sonu">"monu")
print("sonu">"sanjay")
print("ramu"<"Ram")
print("_ramu"<"Ram")
print(10>=10)
print(10<=10)
